# Generated by Django 5.1.6 on 2025-04-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0004_rename_timestamp_maliciousclick_clicked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='advertisement_type',
            field=models.CharField(choices=[('lifestyle', 'Life Style'), ('food_cooking', 'Food and Cooking'), ('electronics_appliances', 'Electronics and Home Appliances'), ('movie', 'Movie'), ('music', 'Music'), ('photography', 'Photography'), ('gaming', 'Gaming'), ('travel', 'Travel')], default='lifestyle', max_length=30),
        ),
    ]
