# Generated by Django 5.1.1 on 2025-03-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='safe_mode',
            field=models.BooleanField(default=True),
        ),
    ]
